Update apps.yaml
BIG-MAP/big-map-registry pull request #109
Opened 2023-07-04 12:19 UTC by moslmn

adding to BIG-MAP app store.
mo.soleymani@kit.edu
wp3

2023-07-07 13:38 UTC, tsthakur commented on apps.yaml
> +SEI-Active learning workflow:
please remove the spaces.

2023-07-09 20:26 UTC, tsthakur requested changes

2023-07-09 20:26 UTC, tsthakur commented on apps.yaml
> +SEI-Active learning workflow:
Sorry, I was not clear before. I meant the spaces in the name, so something like `SEI-Active_learning_workflow`

2023-07-11 09:48 UTC, tsthakur approved these changes

2023-07-11 10:57 UTC, moslmn commented
hi, i miss labeled the categories. sorry about that

2023-07-13 13:40 UTC, tsthakur approved these changes

2023-07-13 13:41 UTC, merged