Apps: Add Appstore Entry for AiiDALab-QE XAS Plugin
BIG-MAP/big-map-registry pull request #163
Opened 2024-02-28 13:23 UTC by PNOGillespie

Adds an Appstore entry for the XAS plugin of AiiDALab-QE

Note that, since the XAS plugin is integrated with AiiDALab-QE, the installation video has been re-used from the `aiidalab-qe` entry.

2024-02-28 13:24 UTC, PNOGillespie commented
@superstar54: Have a look at the metadata and let me know if any changes need to be made.

2024-02-28 15:01 UTC, superstar54 commented
One mirror suggestion on the description:
```
A web-based application designed to calculate X-ray Absorption Near-Edge Spectra (XANES) through Density Functional Theory (DFT) computations. This tool serves as an extension to the AiiDALab-Quantum ESPRESSO application.
```

2024-02-28 17:23 UTC, PNOGillespie commented
Thanks for the reply @superstar54. We discussed the description previously on our side and feel that the original wording is best, since it makes it clear that this is an extension to AiiDALab-QE rather than a separate app.

2024-02-28 17:25 UTC, PNOGillespie commented
We're all ready on our end @tsthakur. Thanks a lot as well for clarifying things along the way.

2024-03-05 11:23 UTC, tsthakur commented on apps.yaml
> +        video_demonstration_url: https://drive.google.com/file/d/1m4imcAzaCJabL9Rjjal4GqqcVwGkIqmU/preview
Can you use this link instead, so that the video is hosted on our end:
https://drive.google.com/file/d/1aoMfAabynAbkXkoktFBJrsKKxTtrFuHs/preview

2024-03-05 11:24 UTC, tsthakur requested changes
Please change the link to the demonstration video.

2024-03-05 11:25 UTC, tsthakur commented on apps.yaml
> +        video_demonstration_url: https://drive.google.com/file/d/1m4imcAzaCJabL9Rjjal4GqqcVwGkIqmU/preview
this is for video demonstration

2024-03-05 13:33 UTC, tsthakur approved these changes

2024-03-05 13:34 UTC, merged

2024-03-05 13:35 UTC, PNOGillespie commented
Thanks @tsthakur!